package Presentacion.Interfaces.Login;

import Datos.DAO.UsuarioDAO;
import Datos.Entidades.Usuario;
import Negocio.ControlLogin;
import Presentacion.Interfaces.PanelImagen;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import Presentacion.Interfaces.ScrollBarCustom;

/**
 *
 * @author sortizu
 */
public class LoginPIN extends javax.swing.JPanel {

   
    public LoginPIN() {
        initComponents();
        setBackground(new Color(0,0,0,0));
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eLiquor = new javax.swing.JLabel();
        PanelPIN = new PanelImagen("/Presentacion/Imagenes/Paneles/Login/PanelListaDeUsuarios.png");
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnSalir = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1360, 768));

        eLiquor.setFont(new java.awt.Font("Roboto Medium", 1, 140)); // NOI18N
        eLiquor.setForeground(new java.awt.Color(255, 255, 255));
        eLiquor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eLiquor.setText("eLiquor");
        eLiquor.setPreferredSize(new java.awt.Dimension(569, 201));

        PanelPIN.setBackground(new java.awt.Color(255, 255, 255));
        PanelPIN.setPreferredSize(new java.awt.Dimension(435, 768));
        PanelPIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/flecha.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelPIN.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 60, 60));

        jSeparator1.setForeground(new java.awt.Color(208, 208, 208));
        jSeparator1.setPreferredSize(new java.awt.Dimension(350, 10));
        PanelPIN.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 370, -1));

        jSeparator2.setForeground(new java.awt.Color(208, 208, 208));
        jSeparator2.setPreferredSize(new java.awt.Dimension(350, 10));
        PanelPIN.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 370, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/flecha.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelPIN.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 60, 60));

        jTextField1.setText("jTextField1");
        PanelPIN.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/Boton Salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnSalir)
                .addContainerGap(1262, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(92, 92, 92)
                    .addComponent(eLiquor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(689, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(283, 283, 283)
                            .addComponent(eLiquor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        /*Utilizando utilidades de swing para obtener la ventana principal (FramePrincipal)
        y cerrar todo el programa*/
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
    }//GEN-LAST:event_btnSalirMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPIN;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel eLiquor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
