/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.Interfaces.Usuarios;

import Datos.Entidades.Usuario;
import Negocio.ControlUsuarios;
import Presentacion.Interfaces.FramePrincipal;
import Presentacion.Interfaces.PanelImagen;
import Presentacion.Interfaces.ScrollBarCustom;
import Presentacion.Utilidades.UtilidadesFuentes;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sortizu
 */
public class EliminarUsuario extends PanelImagen{
    /*Selectores de permisos*/
    
    PanelDeUsuarios panelPrincipalDeModuloUsuarios;
    DefaultTableModel modeloListaDeUsuarios;
    ScrollBarCustom scrollCustom;    
    int[] indicesDeTabla;
    
    public EliminarUsuario(PanelDeUsuarios panelPrincipalDeModuloUsuarios, int[] indicesDeTabla) {
        super("/Presentacion/Imagenes/Paneles/Usuarios/PanelEliminarUsuarios.png");
        initComponents();
        modeloListaDeUsuarios=(DefaultTableModel)ListaDeUsuarios.getModel();
        ListaDeUsuarios.setFont(UtilidadesFuentes.InterExtraLight.deriveFont(25.0f));
        ListaDeUsuarios.setForeground(Color.decode("#8C8C8C"));
        ListaDeUsuarios.setIntercellSpacing(new Dimension(0,0));
        ((DefaultTableCellRenderer)ListaDeUsuarios.getDefaultRenderer(String.class)).setHorizontalAlignment(JLabel.CENTER);
        
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.setOpaque(false);
        scrollCustom=new ScrollBarCustom();
        scrollCustom.setUnitIncrement(16);
        jScrollPane1.setVerticalScrollBar(scrollCustom);
        ListaDeUsuarios.getTableHeader().setUI(null);
        
        this.panelPrincipalDeModuloUsuarios=panelPrincipalDeModuloUsuarios;
        this.indicesDeTabla=indicesDeTabla;
        for (int i: indicesDeTabla) {
            añadirUsuarioALista(panelPrincipalDeModuloUsuarios.usuarios.get(i).getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        Cabecera = new javax.swing.JSeparator();
        lblAGREGARUSUARIOS1 = new javax.swing.JLabel();
        Pie = new javax.swing.JSeparator();
        btnAceptar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDeUsuarios = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(473, 411));
        setMinimumSize(new java.awt.Dimension(473, 411));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(473, 339));
        setVerifyInputWhenFocusTarget(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(UtilidadesFuentes.InterLight.deriveFont(20.0f));
        lblNombre.setForeground(new java.awt.Color(140, 140, 140));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Se eliminarán los siguientes usuarios:");
        lblNombre.setPreferredSize(new java.awt.Dimension(473, 30));
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        Cabecera.setForeground(new java.awt.Color(208, 208, 208));
        Cabecera.setPreferredSize(new java.awt.Dimension(465, 2));
        add(Cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 65, -1, -1));

        lblAGREGARUSUARIOS1.setFont(UtilidadesFuentes.InterLight.deriveFont(30.0f));
        lblAGREGARUSUARIOS1.setForeground(new java.awt.Color(205, 95, 95));
        lblAGREGARUSUARIOS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAGREGARUSUARIOS1.setText("CONFIRMACIÓN");
        lblAGREGARUSUARIOS1.setPreferredSize(new java.awt.Dimension(790, 65));
        add(lblAGREGARUSUARIOS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 473, -1));

        Pie.setForeground(new java.awt.Color(208, 208, 208));
        Pie.setPreferredSize(new java.awt.Dimension(465, 2));
        add(Pie, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 266, -1, -1));

        btnAceptar.setFont(UtilidadesFuentes.InterBlack.deriveFont(30.0f));
        btnAceptar.setForeground(new java.awt.Color(108, 197, 100));
        btnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptar.setText("✓");
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setPreferredSize(new java.awt.Dimension(90, 63));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAceptarMousePressed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 268, -1, -1));

        btnCancelar.setFont(UtilidadesFuentes.InterBlack.deriveFont(30.0f));
        btnCancelar.setForeground(new java.awt.Color(174, 174, 174));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("×");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setPreferredSize(new java.awt.Dimension(90, 63));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 268, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(370, 190));

        ListaDeUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaDeUsuarios.setAutoscrolls(false);
        ListaDeUsuarios.setFocusable(false);
        ListaDeUsuarios.setOpaque(false);
        ListaDeUsuarios.setRequestFocusEnabled(false);
        ListaDeUsuarios.setRowHeight(60);
        ListaDeUsuarios.setRowSelectionAllowed(false);
        ListaDeUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaDeUsuarios.setShowGrid(false);
        ListaDeUsuarios.getTableHeader().setResizingAllowed(false);
        ListaDeUsuarios.getTableHeader().setReorderingAllowed(false);
        ListaDeUsuarios.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(ListaDeUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        ((FramePrincipal)((JFrame) SwingUtilities.getWindowAncestor(this))).cerrarPanelesEmergentes();
    }//GEN-LAST:event_btnCancelarMousePressed

    private void btnAceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMousePressed
        ArrayList<Usuario> usuariosABorrar = new ArrayList<Usuario>();
        ArrayList<Usuario> ListaDeUsuarios = (ArrayList<Usuario>)panelPrincipalDeModuloUsuarios.usuarios;
        for (int i=indicesDeTabla.length-1;i>=0;i--) {
            usuariosABorrar.add(ListaDeUsuarios.get(indicesDeTabla[i]));
            panelPrincipalDeModuloUsuarios.eliminarUsuarioDeLaTabla(ListaDeUsuarios.get(indicesDeTabla[i]));
        }
        ListaDeUsuarios.removeAll(usuariosABorrar);
        ControlUsuarios.eliminarUsuarios(usuariosABorrar);
        ((FramePrincipal)((JFrame) SwingUtilities.getWindowAncestor(this))).cerrarPanelesEmergentes();
    }//GEN-LAST:event_btnAceptarMousePressed

    public void añadirUsuarioALista(String nombre){
        modeloListaDeUsuarios.addRow(new Object[]{nombre});
        //Adaptando el tamaño de la barra de Scroll
        double newScrollBarHeight=Math.pow(jScrollPane1.getPreferredSize().getHeight(),2)/(
                ListaDeUsuarios.getRowHeight()*ListaDeUsuarios.getRowCount());
        
        scrollCustom.setThumbSize((int)newScrollBarHeight);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Cabecera;
    private javax.swing.JTable ListaDeUsuarios;
    private javax.swing.JSeparator Pie;
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAGREGARUSUARIOS1;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
    
    
   
}
