/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.Interfaces.Usuarios;

import Presentacion.Interfaces.Clientes.*;

/**
 *
 * @author sortizu
 */
public class Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form Clientes
     */
    public Usuarios() {
        initComponents();
        setOpaque(false);
        contenedorFuncionesUsuarios.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorFuncionesUsuarios = new javax.swing.JLayeredPane();
        panelDeUsuarios = new Presentacion.Interfaces.Usuarios.PanelDeUsuarios();

        setPreferredSize(new java.awt.Dimension(1360, 768));
        setLayout(new java.awt.BorderLayout());

        contenedorFuncionesUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        contenedorFuncionesUsuarios.add(panelDeUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(contenedorFuncionesUsuarios, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane contenedorFuncionesUsuarios;
    private Presentacion.Interfaces.Usuarios.PanelDeUsuarios panelDeUsuarios;
    // End of variables declaration//GEN-END:variables
}
