/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.Interfaces.Menu;

import Negocio.ControlMenu;
import Presentacion.Interfaces.PanelImagen;
import Presentacion.Utilidades.UtilidadSesion;
import Presentacion.Utilidades.UtilidadesFuentes;
import java.awt.CardLayout;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author sortizu
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu(String nombreUsuario, boolean [] permisos) {
        initComponents();
        setOpaque(false);
        btnModuloVentas.setEnabled(permisos[0]);
        btnModuloUsuarios.setEnabled(permisos[1]);
        btnModuloProveedores.setEnabled(permisos[2]);
        btnModuloClientes.setEnabled(permisos[3]);
        btnModuloInventario.setEnabled(permisos[4]);
        btnModuloReportes.setEnabled(permisos[5]);
        lblUsuario.setText("¡Bienvenido, "+nombreUsuario.split(" ")[0]+"!");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSistema = new PanelImagen("/Presentacion/Imagenes/Paneles/Menu/PanelMenu.png");
        lblNombreLicoreria = new javax.swing.JLabel();
        cabecera = new javax.swing.JSeparator();
        SeparadorDatos1 = new javax.swing.JSeparator();
        lblHora = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblApertura = new javax.swing.JLabel();
        lnlNumTerminal = new javax.swing.JLabel();
        lblCodigoTienda = new javax.swing.JLabel();
        lblHorasAperturadas = new javax.swing.JLabel();
        SeparadorDatos2 = new javax.swing.JSeparator();
        pie = new javax.swing.JSeparator();
        lblMENU = new javax.swing.JLabel();
        PanelDeBotonesDeModulos = new javax.swing.JPanel();
        btnModuloVentas = new javax.swing.JLabel();
        btnModuloInventario = new javax.swing.JLabel();
        btnModuloReportes = new javax.swing.JLabel();
        btnModuloClientes = new javax.swing.JLabel();
        btnModuloProveedores = new javax.swing.JLabel();
        btnModuloUsuarios = new javax.swing.JLabel();
        lblNombreDeSistema = new javax.swing.JLabel();
        lvlversion = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnConfiguracion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1360, 768));
        setPreferredSize(new java.awt.Dimension(1360, 768));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSistema.setBackground(new java.awt.Color(255, 255, 255));
        PanelSistema.setPreferredSize(new java.awt.Dimension(928, 768));
        PanelSistema.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreLicoreria.setFont(UtilidadesFuentes.InterRegular.deriveFont(15.0f));
        lblNombreLicoreria.setForeground(new java.awt.Color(140, 140, 140));
        lblNombreLicoreria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreLicoreria.setText("Licoreria \"Ruta 99\"");
        PanelSistema.add(lblNombreLicoreria, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 0, 850, 30));

        cabecera.setForeground(new java.awt.Color(208, 208, 208));
        cabecera.setPreferredSize(new java.awt.Dimension(850, 10));
        PanelSistema.add(cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 30, -1, 10));

        SeparadorDatos1.setForeground(new java.awt.Color(208, 208, 208));
        SeparadorDatos1.setPreferredSize(new java.awt.Dimension(700, 10));
        PanelSistema.add(SeparadorDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 250, -1, 10));

        lblHora.setFont(UtilidadesFuentes.InterBlack.deriveFont(90.0f));
        lblHora.setForeground(new java.awt.Color(88, 88, 88));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("12:00");
        lblHora.setPreferredSize(new java.awt.Dimension(850, 110));
        PanelSistema.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 30, -1, 100));

        lblDia.setFont(UtilidadesFuentes.InterBlack.deriveFont(30.0f));
        lblDia.setForeground(new java.awt.Color(88, 88, 88));
        lblDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDia.setText("9 de octubre de 2020");
        lblDia.setPreferredSize(new java.awt.Dimension(850, 16));
        PanelSistema.add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 130, -1, 40));

        lblUsuario.setFont(UtilidadesFuentes.InterBlack.deriveFont(50.0f));
        lblUsuario.setForeground(new java.awt.Color(88, 88, 88));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("¡Bienvenido, Usuario!");
        lblUsuario.setPreferredSize(new java.awt.Dimension(850, 16));
        PanelSistema.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 176, -1, 70));

        lblApertura.setFont(UtilidadesFuentes.InterRegular.deriveFont(20.0f));
        lblApertura.setForeground(new java.awt.Color(140, 140, 140));
        lblApertura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApertura.setText("Aperturado hace:");
        lblApertura.setMaximumSize(new java.awt.Dimension(280, 50));
        lblApertura.setMinimumSize(new java.awt.Dimension(280, 50));
        lblApertura.setPreferredSize(new java.awt.Dimension(165, 50));
        PanelSistema.add(lblApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 256, -1, -1));

        lnlNumTerminal.setFont(UtilidadesFuentes.InterRegular.deriveFont(25.0f));
        lnlNumTerminal.setForeground(new java.awt.Color(140, 140, 140));
        lnlNumTerminal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnlNumTerminal.setText("Terminal: 1");
        lnlNumTerminal.setMaximumSize(new java.awt.Dimension(280, 50));
        lnlNumTerminal.setMinimumSize(new java.awt.Dimension(280, 50));
        lnlNumTerminal.setPreferredSize(new java.awt.Dimension(280, 50));
        PanelSistema.add(lnlNumTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        lblCodigoTienda.setFont(UtilidadesFuentes.InterRegular.deriveFont(20.0f));
        lblCodigoTienda.setForeground(new java.awt.Color(140, 140, 140));
        lblCodigoTienda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodigoTienda.setText("Codigo de Tienda: XW962");
        lblCodigoTienda.setMaximumSize(new java.awt.Dimension(280, 50));
        lblCodigoTienda.setMinimumSize(new java.awt.Dimension(280, 50));
        lblCodigoTienda.setPreferredSize(new java.awt.Dimension(280, 50));
        PanelSistema.add(lblCodigoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 256, -1, -1));

        lblHorasAperturadas.setFont(UtilidadesFuentes.InterRegular.deriveFont(50.0f));
        lblHorasAperturadas.setForeground(new java.awt.Color(140, 140, 140));
        lblHorasAperturadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHorasAperturadas.setText("04:00 H");
        lblHorasAperturadas.setToolTipText("");
        lblHorasAperturadas.setMaximumSize(new java.awt.Dimension(220, 90));
        lblHorasAperturadas.setMinimumSize(new java.awt.Dimension(220, 90));
        lblHorasAperturadas.setPreferredSize(new java.awt.Dimension(220, 90));
        PanelSistema.add(lblHorasAperturadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 270, -1, -1));

        SeparadorDatos2.setForeground(new java.awt.Color(208, 208, 208));
        SeparadorDatos2.setPreferredSize(new java.awt.Dimension(800, 10));
        PanelSistema.add(SeparadorDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 360, -1, -1));

        pie.setForeground(new java.awt.Color(208, 208, 208));
        pie.setPreferredSize(new java.awt.Dimension(850, 2));
        PanelSistema.add(pie, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 738, -1, -1));

        lblMENU.setFont(UtilidadesFuentes.InterRegular.deriveFont(35.0f));
        lblMENU.setForeground(new java.awt.Color(140, 140, 140));
        lblMENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMENU.setText("MENÚ");
        lblMENU.setMaximumSize(new java.awt.Dimension(280, 50));
        lblMENU.setMinimumSize(new java.awt.Dimension(280, 50));
        lblMENU.setPreferredSize(new java.awt.Dimension(850, 50));
        PanelSistema.add(lblMENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, -1, -1));

        PanelDeBotonesDeModulos.setBackground(new java.awt.Color(255, 255, 255));
        PanelDeBotonesDeModulos.setPreferredSize(new java.awt.Dimension(800, 310));
        PanelDeBotonesDeModulos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btnModuloVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/Boton Ventas.png"))); // NOI18N
        btnModuloVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDeBotonesDeModulos.add(btnModuloVentas);

        btnModuloInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/Boton Inventario.png"))); // NOI18N
        btnModuloInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDeBotonesDeModulos.add(btnModuloInventario);

        btnModuloReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/Boton Reportes.png"))); // NOI18N
        btnModuloReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDeBotonesDeModulos.add(btnModuloReportes);

        btnModuloClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/Boton Clientes.png"))); // NOI18N
        btnModuloClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDeBotonesDeModulos.add(btnModuloClientes);

        btnModuloProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/Boton Proveedores.png"))); // NOI18N
        btnModuloProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDeBotonesDeModulos.add(btnModuloProveedores);

        btnModuloUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/Boton Usuarios.png"))); // NOI18N
        btnModuloUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModuloUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModuloUsuariosMousePressed(evt);
            }
        });
        PanelDeBotonesDeModulos.add(btnModuloUsuarios);

        PanelSistema.add(PanelDeBotonesDeModulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 365, -1, 310));

        lblNombreDeSistema.setFont(UtilidadesFuentes.InterRegular.deriveFont(15.0f));
        lblNombreDeSistema.setForeground(new java.awt.Color(140, 140, 140));
        lblNombreDeSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreDeSistema.setText("POS eLiquor");
        lblNombreDeSistema.setPreferredSize(new java.awt.Dimension(425, 30));
        PanelSistema.add(lblNombreDeSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 738, -1, -1));

        lvlversion.setFont(UtilidadesFuentes.InterRegular.deriveFont(15.0f));
        lvlversion.setForeground(new java.awt.Color(140, 140, 140));
        lvlversion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lvlversion.setText("V 1.0");
        lvlversion.setPreferredSize(new java.awt.Dimension(425, 30));
        PanelSistema.add(lvlversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 738, -1, -1));

        add(PanelSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/Boton Salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });
        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 689, -1, 80));

        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/Boton Config.png"))); // NOI18N
        btnConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1265, 688, -1, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/Boton Ayuda.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1265, 7, -1, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        /*Utilizando utilidades de swing para obtener la ventana principal (FramePrincipal)
        y cerrar todo el programa*/
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnModuloUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloUsuariosMousePressed
        JPanel parent = (JPanel)getParent();
        CardLayout layout = (CardLayout) parent.getLayout();
        Presentacion.Interfaces.Usuarios.Usuarios usuarios = new Presentacion.Interfaces.Usuarios.Usuarios();
        parent.add("usuarios",usuarios);
        layout.show(parent, "usuarios");
    }//GEN-LAST:event_btnModuloUsuariosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDeBotonesDeModulos;
    private javax.swing.JPanel PanelSistema;
    private javax.swing.JSeparator SeparadorDatos1;
    private javax.swing.JSeparator SeparadorDatos2;
    private javax.swing.JLabel btnConfiguracion;
    private javax.swing.JLabel btnModuloClientes;
    private javax.swing.JLabel btnModuloInventario;
    private javax.swing.JLabel btnModuloProveedores;
    private javax.swing.JLabel btnModuloReportes;
    private javax.swing.JLabel btnModuloUsuarios;
    private javax.swing.JLabel btnModuloVentas;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JSeparator cabecera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApertura;
    private javax.swing.JLabel lblCodigoTienda;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHorasAperturadas;
    private javax.swing.JLabel lblMENU;
    private javax.swing.JLabel lblNombreDeSistema;
    private javax.swing.JLabel lblNombreLicoreria;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lnlNumTerminal;
    private javax.swing.JLabel lvlversion;
    private javax.swing.JSeparator pie;
    // End of variables declaration//GEN-END:variables
}
